language: scala
scala:
- 2.11.6
env:
  global:
    # Used to decrypt the GPG keys and the credentials files. They are used for signing this project's artifacts and publishing them to Maven Central via Sonatype
  - secure: k1SZQy/GPJyxsfPoJuNcQ+eAvX8t3/rdnL35ghNf4ME1IjVAEYvI6R0zFpU9UITlIZOXa9lz7QeRpHVBomN0zv4A0ShjmHgB1vX+YJFA3Jr+phUNLQZscKwieJrcJyM9i3UpKlMiPWFGiaGQyChl1LY76i3yN720fwVS6vQHIUHgNoYScFXf2lLDzf49lz1qMCiQ3czifPiNmMVsrQZ5kAu7HrKcQw+KL7WvHWJn7+ObEADof4EqNf9LMf2S+kWtPrFJkxKJFyuKYIwtFFVnckDGgfjIbzEgBIWNVMPhspeCfYj6q8fXbBpfP+h26WdsvVFzORh+Szjs5ogI6YjWCX6BohUQaPDmW0cakzOxtPHK4VYrC/r/fW8xSXL2yPuvQOXE3S7fNZs3IVQcsH2LB1YHiG4MD47z6ueij6Sm5gG4nGpOrkTPyguEUvy2PiIBy84qXA61tY2GwPhFoTtpn+St5DbQP43CqMxnCVRWP+Mq999Jg2yfUxCgTD4A4BpgTUwnond1ofGFvWjFWMes33Z9H1XjMY+igjgIg4BR99/d39DEs9w17hZui4nGqF1Rvldj6x2shV2fYWgKIoI0k1xg1OpwHslIc3FtwaFf5N1wYYLA0dyp2z/Zh193gpR0KBafQrtuqyO6vY2xFMuNGn3nevicjOXeI+X2flh6X4s=

before_install:
  # Decrypt the secrets
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.asc.enc -out local.secring.asc -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.asc.enc -out local.pubring.asc -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in credentials.sbt.enc -out local.credentials.sbt -d

after_success:
- sbt publishSigned
- sbt sonatypeRelease

